language: ruby
rvm:
  - 1.9.3
services:
  - mongodb
  - elasticsearch
env: ELASTICSEARCH_INDEX_URL=http://localhost:9200/
script: "bundle exec rake test:all"
notifications:
  irc: "irc.freenode.org#rstatus"
